### ISSUE TITLE
Contributor

### ISSUE THREAD

**Issue by olamiko** [wmww/Pinecone#20]
Hi, I will like to contribute to Pinecode. Even though I am a beginner in creating a language, I can help. Please provide enough documentation to the language internals to make it practical for me to contribute @wmww

**Comment by olamiko** [comment]
@wmww

**Comment by wmww** [comment]
Anyway, I wouldn't say I recommend working on Pinecone, as it doesn't appear to have much of a future and I don't have time to help much. If you're curious, however, feel free to wack at it as much as you want. Might learn something, might make something cool. idk.
