### ISSUE TITLE
Is Pinecone abandoned?

### ISSUE THREAD

**Issue by Alihusejn** [wmww/Pinecone#23]

**Comment by wmww** [comment]
Yes. It served its purpose as a learning project, but my "implement first ask questions later" approach began to catch up with me. Language design is complex field, and not realizing I would ever actually get something usable, I didn't put too much thought into it at the beginning. As such, if I want to work on a PL again, I will likely start fresh.

**Comment by MrazTevin** [comment]
What if there are other interested participants who want to continue developing the pinecone project for instance, do they stand a chance?

**Comment by wmww** [comment]
IIRC, the code isn't *that* bad so... in theory... yes? I suppose. I can't be of much help, as I haven't worked on it much in over a year and remember little. Then again, **no one** has worked on it much in over a year, so I doubt those hypothetical interested participants exist.

**Comment by MrazTevin** [comment]
@wmww I understand that language design Is a really complex field. But you never know participants may show up any time any moment. Like I may be interested in this project of yours if I get to understand it very well. Who knows maybe it might be even the next python.👋
