### ISSUE TITLE
What does the name Pinecone mean?

### ISSUE THREAD

**Issue by lukefisklennon** [wmww/Pinecone#25]
Hi there,

I know this project is abandoned, but I'm intrigued about the name. Why *Pinecone*? What is its meaning/significance for this language?

Thanks!

**Comment by MrazTevin** [comment]
The significance of this language was for learning purposes, which I believe has been accomplished by the Author as described in the ReadMe section.

**Comment by wmww** [comment]
> Why _Pinecone_?

I don't remember. @twof?
