### ISSUE TITLE
Interpreter Source code

### ISSUE THREAD

**Issue by awojobigodfrey** [wmww/Pinecone#37]
I saw your blog post which I loved, I am also trying to create my PL in python/js, I have seen your lexer and parser source code, but where is the interpreters own.

**Comment by wmww** [comment]
I believe most of the code for running programs is here: https://github.com/wmww/Pinecone/tree/master/src/Actions, but it's been way to long for me to really remember.

**Comment by awojobigodfrey** [comment]
Ok tnx
